### ISSUE TITLE
register KGCL with LOV and BioPortal

### ISSUE THREAD

**Issue by cmungall** [INCATools/kgcl#17]
As soon as https://w3id.org/kgcl/kgcl.owl.ttl resolves (https://github.com/perma-id/w3id.org/pull/3020) then register KGCL owl artefact with BP, LOV, ...

**Comment by hrshdhgd** [comment]
https://bioportal.bioontology.org/ontologies/KGCL Done!

**Comment by hrshdhgd** [comment]
I just did BioPortal. I don't know what LOV is.
