### ISSUE TITLE
update bioregistry dependency to ^0.6.0

### ISSUE THREAD

**Issue by sierra-moxon** [INCATools/kgcl#23]
this issue: [](https://github.com/biopragmatics/bioregistry/issues/705) is causing issues deploying reasoner-validator (depends on BMT, depends on oaklib, depends on bioregistry and oaklib depends on kgcl ) to ITRB environments.  I think the fix here is to update oaklib pyproject.toml to version ^0.6.0 of bioregistry, and to do that, we need to update kgcl to use bioregistry ^0.6.0

**Comment by sierra-moxon** [comment]
also if I could have repo push permissions, I can make the fix: 
```
remote: Permission to INCATools/kgcl.git denied to sierra-moxon.
fatal: unable to access 'https://github.com/INCATools/kgcl/': The requested URL returned error: 403
```

**Comment by cmungall** [comment]
looks like this is done...

but there should be no reason for a library whose only job is to parse KGCL should have a dependency on a prefix registry
