### ISSUE TITLE
modify grammar to remove need for <>s on URIs

### ISSUE THREAD

**Issue by cmungall** [INCATools/kgcl#7]
[kgcl.lark](https://github.com/INCATools/kgcl/blob/main/src/kgcl_schema/grammar/kgcl.lark) has:

```
_entity: ID
         | LABEL 
         | CURIE

...

ID :  "<" INNER_ID ">" 

INNER_ID: /((?!>).)*/
```

This is a bit confusing, as CURIEs *are* IDs

I think what is meant by ID here is actually IRI, so I would change ID to IRI

We also want to make the <>s optional (and deprecated, so I would change to)

```
_entity: IRI
         | LABEL 
         | CURIE

...

IRI: quoted_iri direct_iri
quoted_iri: "<" direct_iri ">
quoted_iri: /((?!>).)*/
```

You will also need to update:

https://github.com/INCATools/kgcl/blob/fdcaddece2319029db4a73cf1a553e166669c3d5/src/kgcl_schema/grammar/parser.py#L501-L518

**Comment by hrshdhgd** [comment]
`IRI` is already defined on line 74

```

IRI: /((?!>>)\S)+/
     | /((?!>>>)\S)+/

```
