### ISSUE TITLE
Fix bioportal/OWL view of KGCL

### ISSUE THREAD

**Issue by cmungall** [INCATools/kgcl#86]
https://bioportal.bioontology.org/ontologies/KGCL/?p=classes&conceptid=root

<img width="397" alt="image" src="https://github.com/user-attachments/assets/1fc6c518-55c0-4f0a-92cc-64f7c173fb2c">

**Comment by cmungall** [comment]
@caufieldjh we can fix this on our 1-on-1

**Comment by cmungall** [comment]
https://github.com/linkml/linkml/issues/2353

**Comment by cmungall** [comment]
https://w3id.org/kgcl/kgcl.owl.ttl still has non-DL axioms and hence ErrorNs show up in bioportal

I think running `make all` on fresh main will fix, let's close when BP looks good

**Comment by nlharris** [comment]
BP (https://bioportal.bioontology.org/ontologies/KGCL/?p=classes&conceptid=root) looks good now, ok to close?

**Comment by caufieldjh** [comment]
Yes - looks good!
